# -*- coding: utf-8 -*-
# AUTO-GENERATED by add_library.py -- do not edit by hand.
# EXTRA_IDENTIFY: (key, needles, product)  |  EXTRA_CVES: {id,product,min,max,desc,cvss,type,...}

EXTRA_IDENTIFY = [
    ('libvips', ['libvips', 'vips'], 'libvips'),
]

EXTRA_CVES = [
    {'id': 'CVE-2018-7998', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'In libvips before 8.6.3, a NULL function pointer dereference vulnerability was found in the vips_region_generate function in region.c, which allows remote attackers to cause a denial of service or possibly have unspecifi', 'cvss': 7.5, 'type': 'unverified', 'remote': None, 'fixed_in': None},
    {'id': 'CVE-2019-6976', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'libvips before 8.7.4 generates output images from uninitialized memory locations when processing corrupted input image data because iofuncs/memory.c does not zero out allocated memory. This can result in leaking raw proc', 'cvss': 5.3, 'type': 'unverified', 'remote': None, 'fixed_in': None},
    {'id': 'CVE-2019-17534', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'vips_foreign_load_gif_scan_image in foreign/gifload.c in libvips before 8.8.2 tries to access a color map before a DGifGetImageDesc call, leading to a use-after-free.', 'cvss': 8.8, 'type': 'unverified', 'remote': None, 'fixed_in': None},
    {'id': 'CVE-2020-20739', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'im_vips2dz in /libvips/libvips/deprecated/im_vips2dz.c in libvips before 8.8.2 has an uninitialized variable which may cause the leakage of remote server path or stack address.', 'cvss': 5.3, 'type': 'unverified', 'remote': None, 'fixed_in': None},
    {'id': 'CVE-2021-27847', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'Division-By-Zero vulnerability in Libvips 8.10.5 in the function vips_eye_point, eye.c#L83, and function vips_mask_point, mask.c#L85.', 'cvss': 6.5, 'type': 'unverified', 'remote': None, 'fixed_in': None},
    {'id': 'CVE-2021-45928', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'libjxl b02d6b9, as used in libvips 8.11 through 8.11.2 and other products, has an out-of-bounds write in jxl::ModularFrameDecoder::DecodeGroup (called from jxl::FrameDecoder::ProcessACGroup and jxl::ThreadPool::RunCallSt', 'cvss': 5.5, 'type': 'unverified', 'remote': None, 'fixed_in': None},
    {'id': 'CVE-2022-24720', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'image_processing is an image processing wrapper for libvips and ImageMagick/GraphicsMagick. Prior to version 1.12.2, using the `#apply` method from image_processing to apply a series of operations that are coming from un', 'cvss': 9.8, 'type': 'unverified', 'remote': None, 'fixed_in': None},
    {'id': 'CVE-2023-40032', 'product': 'libvips', 'min': None, 'max': None, 'desc': 'libvips is a demand-driven, horizontally threaded image processing library. A specially crafted SVG input can cause libvips versions 8.14.3 or earlier to segfault when attempting to parse a malformed UTF-8 character. Use', 'cvss': 5.5, 'type': 'unverified', 'remote': None, 'fixed_in': None},
]
