# -*- coding: utf-8 -*-
"""
VulnScan - auto library expansion (add_library).

When you scan a new product (Ali, Tencent, any vendor) you'll hit third-party
libraries that are not in the built-in CVE db. This tool:
  1) discovers those unrecognized third-party candidates in a directory
  2) adds an identification rule for one of them
  3) auto-fetches that library's CVEs from NVD (no key needed, rate-limited)
     and appends them as "unverified" entries to data/extra_products.py

Everything user-added lives in data/extra_products.py (never touches the
built-in db), and vulnscan picks it up automatically on the next scan.

Usage:
    python add_library.py discover <dir>
    python add_library.py add <product> <needle> [needle2 ...] [--no-cve] [--limit N] [--min-cvss X]
    python add_library.py fetch <product> [--limit N] [--min-cvss X]
"""

import os
import sys
import json
import time
import argparse
import urllib.request
import urllib.parse
import urllib.error

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
EXTRA_FILE = os.path.join(DATA, "extra_products.py")

sys.path.insert(0, HERE)
import cve_match
import vulnscan


def _load_extra():
    """Return {'identify': [...], 'cves': [...]} from extra file (or empty)."""
    empty = {"identify": [], "cves": []}
    if not os.path.exists(EXTRA_FILE):
        return empty
    import importlib.util
    spec = importlib.util.spec_from_file_location("extra_products", EXTRA_FILE)
    m = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(m)
    except Exception:
        return empty
    return {"identify": list(getattr(m, "EXTRA_IDENTIFY", []) or []),
            "cves": list(getattr(m, "EXTRA_CVES", []) or [])}


def _save_extra(extra):
    os.makedirs(DATA, exist_ok=True)
    lines = ["# -*- coding: utf-8 -*-",
             "# AUTO-GENERATED by add_library.py -- do not edit by hand.",
             "# EXTRA_IDENTIFY: (key, needles, product)  |  EXTRA_CVES: {id,product,min,max,desc,cvss,type,...}",
             "",
             "EXTRA_IDENTIFY = ["]
    for key, needles, product in extra["identify"]:
        nd = ", ".join(repr(n) for n in needles)
        lines.append(f'    ({key!r}, [{nd}], {product!r}),')
    lines.append("]")
    lines.append("")
    lines.append("EXTRA_CVES = [")
    for c in extra["cves"]:
        items = ", ".join(f"{k!r}: {v!r}" for k, v in c.items())
        lines.append("    {" + items + "},")
    lines.append("]")
    lines.append("")
    with open(EXTRA_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    cve_match.EXTRA = None  # force reload next time


def discover_unknown(entries):
    """Return unrecognized non-system lib candidates: {name, count, sample}."""
    from collections import Counter
    counts = Counter()
    samples = {}
    for e in entries:
        if vulnscan.is_system_lib(e):
            continue
        if cve_match.identify_product(e)[0]:
            continue
        name = e.get("name", "")
        if not name:
            continue
        counts[name] += 1
        if name not in samples:
            samples[name] = e.get("path") or ""
    return [{"name": n, "count": c, "sample": samples[n]}
            for n, c in counts.most_common()]


def _fetch_nvd_cves(product, limit=60, min_cvss=0):
    """Pull CVEs from NVD by keyword. No API key (rate-limited)."""
    base = "https://services.nvd.nist.gov/rest/json/cves/2.0"
    out = []
    start = 0
    while len(out) < limit and start < 2000:
        q = urllib.parse.urlencode({"keywordSearch": product, "resultsPerPage": 100,
                                    "startIndex": start})
        try:
            req = urllib.request.Request(base + "?" + q)
            with urllib.request.urlopen(req, timeout=30) as r:
                data = json.loads(r.read().decode("utf-8"))
        except Exception as e:
            print(f"  [NVD] fetch error: {e}")
            break
        vulns = data.get("vulnerabilities", [])
        if not vulns:
            break
        for v in vulns:
            c = v.get("cve", {})
            cvss = 0
            for k in ("cvssMetricV31", "cvssMetricV30", "cvssMetricV2"):
                if c.get("metrics", {}).get(k):
                    cvss = c["metrics"][k][0]["cvssData"]["baseScore"]
                    break
            if cvss < min_cvss:
                continue
            desc = ""
            for d in c.get("descriptions", []):
                if d.get("lang") == "en":
                    desc = d.get("value", "")[:220]
                    break
            out.append({"id": c.get("id", ""), "desc": desc, "cvss": cvss})
        start += 100
        time.sleep(6.5)  # NVD no-key limit ~5/30s
    return out[:limit]


def add_product(product, needles, fetch_cve=True, limit=60, min_cvss=0):
    extra = _load_extra()
    key = product.lower()
    added_id = 0
    added_cve = 0
    exists = any(it[0] == key for it in extra["identify"])
    if not exists:
        extra["identify"].append((key, list(needles), key))
        added_id = 1
    if fetch_cve:
        print(f"[*] 从 NVD 拉取 {product} 的 CVE ...")
        fetched = _fetch_nvd_cves(product, limit, min_cvss)
        existing = {c["id"] for c in extra["cves"]}
        for f in fetched:
            if f["id"] in existing:
                continue
            extra["cves"].append({"id": f["id"], "product": key, "min": None, "max": None,
                                  "desc": f["desc"], "cvss": f["cvss"],
                                  "type": "unverified", "remote": None, "fixed_in": None})
            added_cve += 1
        print(f"[*] NVD 拉到 {len(fetched)} 条候选，新增 {added_cve} 条")
    _save_extra(extra)
    return {"identify_added": added_id, "cves_added": added_cve}


def main():
    ap = argparse.ArgumentParser(description="VulnScan 自动加库")
    sub = ap.add_subparsers(dest="cmd", required=True)

    d = sub.add_parser("discover", help="发现目录里未识别的第三方库候选")
    d.add_argument("dir", help="要扫描的目录")

    a = sub.add_parser("add", help="加一个库（识别规则 + 可选拉取 CVE）")
    a.add_argument("product", help="库名，如 libvips")
    a.add_argument("needle", nargs="+", help="文件名/描述匹配标识，如 libvips vips")
    a.add_argument("--no-cve", action="store_true", help="只加识别，不拉 CVE")
    a.add_argument("--limit", type=int, default=60)
    a.add_argument("--min-cvss", type=float, default=0)

    f = sub.add_parser("fetch", help="只拉某库的 CVE 追加进库")
    f.add_argument("product")
    f.add_argument("--limit", type=int, default=60)
    f.add_argument("--min-cvss", type=float, default=0)

    args = ap.parse_args()

    if args.cmd == "discover":
        if not os.path.isdir(args.dir):
            print(f"[错误] 不是有效目录: {args.dir}")
            return 1
        if not os.path.isfile(vulnscan.SCANNER):
            print(f"[错误] 找不到引擎: {vulnscan.SCANNER}")
            return 1
        print(f"[*] 扫描 {args.dir} 找未识别第三方库 ...")
        entries, stderr = vulnscan.run_scanner(args.dir, None)
        cand = discover_unknown(entries)
        print(f"[*] 共 {len(entries)} 文件，未识别非系统库候选 {len(cand)} 个：")
        for c in cand[:40]:
            print(f"   {c['name']:<34} x{c['count']}   {c['sample']}")
        print("\n要加库：  python add_library.py add <库名> <匹配标识> [--limit 60]")
        return 0

    if args.cmd == "add":
        r = add_product(args.product, args.needle, fetch_cve=not args.no_cve,
                        limit=args.limit, min_cvss=args.min_cvss)
        print(f"[*] 完成：识别规则 {r['identify_added']} 条，CVE 新增 {r['cves_added']} 条")
        print(f"[*] 已写入 {EXTRA_FILE}，下次扫描自动生效")
        return 0

    if args.cmd == "fetch":
        extra = _load_extra()
        key = args.product.lower()
        if not any(it[0] == key for it in extra["identify"]):
            print(f"[!] 提示：{args.product} 还没有识别规则，先 add 或只 fetch 的 CVE 不会命中")
        added_cve = add_product(args.product, [args.product], fetch_cve=True,
                                limit=args.limit, min_cvss=args.min_cvss)["cves_added"]
        print(f"[*] CVE 新增 {added_cve} 条")
        return 0


if __name__ == "__main__":
    sys.exit(main())
